on: [push]

permissions:
  contents: read
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Publish docs
    steps:
      - uses: actions/checkout@v3
      - name: Publish docs
        uses: mikaelvesavuori/documentarian-action@v1.0.0
        with:
          schema_path: api/asyncapi.json
          #catalogist_endpoint: ${{ secrets.CATALOGIST_ENDPOINT }}
          #catalogist_api_key: ${{ secrets.CATALOGIST_API_KEY }}
          #cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          #cloudflare_auth_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          #cloudflare_project_name: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          #cloudflare_catalog_name: eventcatalog
      - name: 'Check'
        run: |
          cd docs
          ls -A
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: SBOM
          path: docs/syft.txt